### ISSUE TITLE
폴더 탐색

### ISSUE THREAD

**Issue by uthline** [ddorii/Pythoner#1]
1. 폴더위치를 입력
2. 해당 폴더의 sub-folder의 갯수와 파일의 갯수를 계산하는 프로그램

예)
위치를 입력해주세요: C:\Users
폴더: 30개, 파일 4000개

**Comment by uthline** [comment]
os module
recursive function

**Comment by uthline** [comment]
소스 분석했니?

**Comment by uthline** [comment]
@ddorii 닫아줘

**Comment by ddorii** [comment]
import os

path = input("폴더 위치를 입력해주세요:")

def get_number_of_sub_file_dir(path):
    files = 0
    dirs = 0
    list = [os.path.join(path, i) for i in os.listdir(path)]
    for p in list:
        if os.path.isfile(p):
            files += 1
        elif os.path.isdir(p):
            dirs += 1
            sub_files, sub_dirs = get_number_of_sub_file_dir(p)
            files += sub_files
            dirs += sub_dirs
    return files, dirs


f, d = get_number_of_sub_file_dir(path)
print("파일: {}, 폴더: {}".format(f, d))
